apiVersion: v1
kind: Service
metadata:
  name: stealth-browser
  namespace: middleware
  labels:
    app: stealth-browser
spec:
  type: ClusterIP
  selector:
    app: stealth-browser
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: novnc
    port: 6080
    targetPort: 6080
    protocol: TCP
