apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stealth-browser-api-route
  namespace: stealth-browser
  labels:
    app: stealth-browser-cp
spec:
  hostnames:
  - stealth-browser-api.vpc-dale.gimcyun.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: stealth-browser-cp
      port: 8000
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stealth-browser-vnc-route
  namespace: stealth-browser
  labels:
    app: stealth-browser-cp
spec:
  hostnames:
  - stealth-browser-vnc.vpc-dale.gimcyun.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: istio-gateway
    namespace: istio-system
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: stealth-browser-cp
      port: 8000
      weight: 100
    matches:
    - path:
        type: PathPrefix
        value: /
