apiVersion: v1
kind: Service
metadata:
  name: stealth-browser-cp
  namespace: stealth-browser
  labels:
    app: stealth-browser-cp
spec:
  type: ClusterIP
  selector:
    app: stealth-browser-cp
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
